version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3002
      - NEXT_PUBLIC_GRAPHQL_API_URL=${NEXT_PUBLIC_GRAPHQL_API_URL:-http://89.232.184.198:3301/graphql}
    volumes:
      # Монтируем директорию с изображениями для обеспечения доступа
      - ./public:/app/public:ro
      # For persistent data storage
      - app_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3002/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  app_data:
